Update README.md
OpenBioML/chemnlp pull request #1
Opened 2023-02-21 14:44 UTC by loftusa

I updated the README to include a brief description about this project and links.

2023-02-22 11:39 UTC, MicPie commented
Hi @loftusa I just left some small comments. Just let me know if you have time to change the few things. No worries if not, then I can do it. Just tell me. 👍

2023-02-22 11:41 UTC, MicPie requested changes
Hi @loftusa I just left some small comments. Just let me know if you have time to change the few things. No worries if not, then I can do it. Just tell me. 😃

2023-02-22 11:41 UTC, MicPie commented on README.md
> +**Project Proposal**: https://docs.google.com/document/d/1C44EKSJRojm39P2CaxnEq-0FGwDRaknKxJ8lZI6xr5M/edit?usp=sharing
To make the links look nicer use [link description](https://xy.com/), see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links for more details.

2023-02-22 11:41 UTC, MicPie commented on README.md
>  # chemnlp
ChemNLP

2023-02-22 11:41 UTC, MicPie commented on README.md
> +ChemNLP is a project that aims to create an extensive chemistry dataset and use it to train large language models (LLMs) for a wide range of chemistry applications. The resulting models will be capab
Maybe remove this sentence until we have some hard data to back that up:
"The resulting models will be capable of predicting properties of materials and molecules, chemical reactions, and even generating computational chemistry code."

2023-02-22 11:41 UTC, MicPie commented on README.md
> +**Github task board**: https://github.com/orgs/OpenBioML/projects/5/views/1
I just added a dataset board too: https://github.com/orgs/OpenBioML/projects/6/views/1

2023-02-22 22:19 UTC, kjappelbaum commented on README.md
> +
## Contributing
ChemNLP is an open-source project - your involvement is warmly welcome! If you're excited to join us, we recommend the following steps:

- 🤔 Looking for ideas? See our [Task Board](https://github.com/orgs/OpenBioML/projects/5/views/1) to see what we may need help with.

- 💡 Have an idea? Create an issue

Feel free to join our [Discord](https://t.co/YMzpevmkiN)!

2023-02-22 22:19 UTC, kjappelbaum commented on README.md
> +
Let's add then the CoC and Contribution Guide later #6

2023-02-23 17:13 UTC, MicPie commented on README.md
> +**Github task board**: https://github.com/orgs/OpenBioML/projects/5/views/1
we don't use that anymore

2023-02-24 15:47 UTC, MicPie commented
Closed this PR as it is superseded by PR https://github.com/OpenBioML/chemnlp/pull/21.

2023-02-24 15:47 UTC, closed without merging