uploading nlmchem to data
OpenBioML/chemnlp pull request #159
Opened 2023-04-07 23:55 UTC by apoorvasrinivasan26

2023-04-08 00:00 UTC, apoorvasrinivasan26 commented
uploading nlmchem [dataset](https://ftp.ncbi.nlm.nih.gov/pub/lu/NLMChem/) based on [this ](https://www.nature.com/articles/s41597-021-00875-1#citeas) paper

2023-04-12 14:11 UTC, MicPie requested changes
Hi Apoorva,
thank you for adding this dataset! 😃
There are just some minor requests.
Just let me know if you can add them, if not I can do that.
Thank you very much for supporting our data gathering efforts. 🙏

2023-04-12 14:11 UTC, MicPie commented on data/nlmchem/transform.py
> +    fn_data_csv = "nlmchem_data_clean.csv"
We always use `data_clean.csv` so we have the same filename in all data directories.

2023-04-12 14:11 UTC, MicPie commented on data/nlmchem/transform.py
> +        "bibtex": """
Format the bibtex entry like shown here https://github.com/OpenBioML/chemnlp/blob/main/data/caco2_wang/transform.py#L110 to avoid the newline breaks.

2023-04-14 19:12 UTC, apoorvasrinivasan26 commented
done! lmk if there are still any changes to be made

2023-04-18 16:15 UTC, MicPie commented
@apoorvasrinivasan26 Thank you very much! PR looks good to me, but currently `https://ftp.ncbi.nlm.nih.gov/pub/lu/NLMChem/` seems to be not reachable on my end, will test later and finalize my review. 😃

2023-04-18 16:20 UTC, MicPie commented
Ok, I could reach the FTP just a couple of seconds later. All works on my end.
@kjappelbaum Just one thing we need to discuss before the merge: Should we move `Abbreviation` column to the targets?

2023-04-21 04:57 UTC, kjappelbaum commented
>Ok, I could reach the FTP just a couple of seconds later. All works on my end.
@kjappelbaum Just one thing we need to discuss before the merge: Should we move the Abbreviation column to the identifiers?

so the meaningful task would here to predict the description given the abbreviation? 
Then I'd move this to to `identifiers`. I'm also not sure what to think of the ids -- If they have no real meaning/systematics I'm not sure if it will help if we try to predict them.

2023-05-03 20:55 UTC, kjappelbaum commented
@MicPie do we want to set `sample` to `False` for the `MeSH_Identifier`?

2023-05-05 12:42 UTC, MicPie approved these changes

2023-05-08 21:12 UTC, kjappelbaum commented on data/nlmchem/meta.yaml
> +      type: categorical
```suggestion
      type: text
```

2023-05-08 21:12 UTC, kjappelbaum commented on data/nlmchem/meta.yaml
> +      type: categorical
```suggestion
      type: string
```

2023-05-08 21:12 UTC, kjappelbaum commented on data/nlmchem/meta.yaml
> +      type: categorical
(will also need to change in the Python code if you agree)

2023-05-16 16:10 UTC, kjappelbaum approved these changes
Looks good to me now, thanks a lot!

2023-05-16 16:24 UTC, merged