Final logo regular in svg
OpenBioML/chemnlp pull request #163
Opened 2023-04-14 01:01 UTC by phalem

2023-04-19 12:53 UTC, MicPie commented
I closed the PR https://github.com/OpenBioML/chemnlp/pull/164 in favor of this one.

2023-04-19 12:54 UTC, MicPie requested changes

2023-04-19 12:54 UTC, MicPie commented on assets/logo/LLcheM.svg
@phalem The background in the reaction vessel is different in the three sag files. Maybe a copy and paste mistake?

2023-04-20 21:38 UTC, phalem commented on assets/logo/chemnlp.svg
I make a combination of two logo which is Model and Dataset into chemnlp. So from the dataset I take the water science that model feed and from the model I take the cube which is our model structure. I hope this what you mean from this.

2023-04-20 21:41 UTC, phalem commented on assets/logo/LLcheM.svg
@MicPie This was a book inside the cube to make it different from chemnlp logo and llcheM logo(model logo)

2023-04-25 09:54 UTC, MicPie commented on assets/logo/chemnlp.svg
Yes, this is great, see my comment above.

2023-04-29 08:24 UTC, phalem commented
> @phalem The logos look great!
> 
> Just two minor things I would like to change:
> 
> 1. Please remove the cap from the bottles. Then it looks a little bit cleaner. I already tried that and it looks a little bit better, see our slides where I already added it without cap: https://docs.google.com/presentation/d/1JkAKJveYsNGtAWoaksU8ykTdrC0aX3FshiFJ13SU6o8/edit#slide=id.g229d2eeb44b_2_0
> 2. Can you make the "ChemNLP" text only one line for the ChemNLP logo?
> 
> Thank you again for the great logo! I really like the book + liquid for the dataset and then the condensed block for the model. rocket

I will proceed in, sorry for being busy and far from the internet. I will PR it, I am sorry if this will take a while. I hope everyone like it.

2023-05-03 13:56 UTC, MicPie commented on README.md
> +<img src="/assets/logo/chemnlp.svg" width="200" height="200">
```suggestion
```

2023-05-03 14:00 UTC, MicPie approved these changes

2023-05-03 14:03 UTC, merged