chore: update names in data schema
OpenBioML/chemnlp pull request #198
Opened 2023-04-24 21:34 UTC by kjappelbaum

Similar to what we discussed. Added also gerund ("ing form"). 
Starting adjusting some examples, will continue and adjust contribution guide upon first feedback.

2023-04-25 07:53 UTC, MicPie approved these changes

2023-04-25 07:53 UTC, MicPie commented on data/caco2_wang/transform.py
> +                    {"noun": "Caco-2 cell effective permeability"},
I was thinking about having a list under the `noun` key, but both would work

2023-04-25 07:53 UTC, MicPie commented on data/cav3_t-type_calcium_channels_butkiewicz/transform.py
> +                    {"gerund": "inhibiting cav3 t-type calcium channels activity"},
the addition of `gerund` is a great idea!

2023-04-25 19:04 UTC, MicPie requested changes

2023-04-25 19:04 UTC, MicPie commented on data/lipophilicity/transform.py
> +                    {"name": "octanol/water distribution coefficient (logD at pH 7.4)"},
name --> noun?

2023-04-25 19:04 UTC, MicPie commented on data/m1_muscarinic_receptor_agonists_butkiewicz/transform.py
> +                        "name": "a positive allosteric modulator of m1 muscarinic activity"
name --> noun?

2023-04-25 19:04 UTC, MicPie commented on data/lipophilicity/transform.py
>                      "http://www.bioassayontology.org/bao#BAO_0002129",
Yaml needs to be recreated?

2023-04-25 19:04 UTC, MicPie commented on data/m1_muscarinic_receptor_agonists_butkiewicz/transform.py
>                  "uris": [],
Yaml needs to be recreated?

2023-04-25 19:04 UTC, MicPie commented on data/m1_muscarinic_receptor_antagonists_butkiewicz/transform.py
>                  "uris": [],
Yaml needs to be recreated?

2023-04-25 19:04 UTC, MicPie commented on data/orexin1_receptor_butkiewicz/transform.py
>                  "uris": ["http://purl.bioontology.org/ontology/SNOMEDCT/838464006"],
Yaml needs to be recreated?

2023-04-25 19:04 UTC, MicPie commented on data/pampa_ncats/transform.py
>                  "uris": ["http://purl.bioontology.org/ontology/MESH/D002463"],
Yaml needs to be recreated?

2023-04-25 19:04 UTC, MicPie commented on data/potassium_ion_channel_kir2_1_butkiewicz/transform.py
>                  "uris": ["http://purl.obolibrary.org/obo/XCO_0000225"],
Yaml needs to be recreated?

2023-04-25 19:52 UTC, kjappelbaum commented on data/flashpoint/meta.yaml
>  ---
not so sure. This here follows the originally anticipated pattern that the meta.yaml is read in Python

2023-04-25 19:52 UTC, kjappelbaum commented on data/cav3_t-type_calcium_channels_butkiewicz/transform.py
> +                    {"verb": "inhibts cav3 t-type calcium channels"},
Done, thanks

2023-04-25 19:53 UTC, kjappelbaum commented on data/cav3_t-type_calcium_channels_butkiewicz/transform.py
>                  "uris": ["http://purl.obolibrary.org/obo/CHEBI_194338"],
Done

2023-04-25 19:53 UTC, kjappelbaum commented on data/choline_transporter_butkiewicz/transform.py
>              },
Done

2023-04-25 20:48 UTC, kjappelbaum reviewed
@MicPie i think it should be ok now

2023-04-26 10:56 UTC, MicPie requested changes

2023-04-26 10:56 UTC, MicPie commented on data/m1_muscarinic_receptor_agonists_butkiewicz/transform.py
> +                        "name": "a positive allosteric modulator of m1 muscarinic activity"
@kjappelbaum maybe uncommited/unpushed change?

2023-04-26 12:37 UTC, merged