Add Carcinogens from TDC
OpenBioML/chemnlp pull request #55
Opened 2023-03-02 06:25 UTC by phalem

2023-03-02 10:22 UTC, kjappelbaum commented on data/Carcinogens/meta.yaml
> +  - random id
```suggestion
```

2023-03-02 10:23 UTC, kjappelbaum commented on data/Carcinogens/meta.yaml
> +url: https://tdcommons.ai/single_pred_tasks/tox/#carcinogens
```suggestion
```

2023-03-02 10:23 UTC, kjappelbaum commented on data/Carcinogens/meta.yaml
> +  description: corresponding publication
```suggestion
  description: corresponding publication
 - url: https://tdcommons.ai/single_pred_tasks/tox/#carcinogens
   description: original dataset
```

2023-03-02 15:24 UTC, phalem reviewed
remove compound id

2023-04-26 16:35 UTC, kjappelbaum commented on data/carcinogens/meta.yaml
> +          - noun: substance, radionuclide, or radiation that promotes carcinogenesis
```suggestion
          - noun: substance that promotes carcinogenesis
```

2023-04-26 16:36 UTC, kjappelbaum requested changes
one suggestion, otherwise lgtm!

2023-04-26 16:36 UTC, kjappelbaum commented on data/carcinogens/meta.yaml
> +          - http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C347
```suggestion
```
doesn't resolve for me

2023-05-02 13:41 UTC, MicPie approved these changes
thank you all! 😃 lgtm, will merge

2023-05-03 05:58 UTC, kjappelbaum approved these changes

2023-05-03 05:58 UTC, merged