Add Tox21 consist of 12 assay with URI include
OpenBioML/chemnlp pull request #77
Opened 2023-03-08 15:53 UTC by phalem

2023-04-11 13:02 UTC, MicPie commented
@phalem I just added the changes black needs to pass the commit hooks. You can simply get black to add the changes if you run `black .` in the main directory (so no need to search for the changes in the logs on GitHub).

2023-04-12 17:00 UTC, MicPie commented
Note: We need to define the target description properly. So far I changed it to include the assay name. Maybe we should discuss a more unspecific setup?

2023-04-14 00:49 UTC, phalem commented
@MicPie  Great work! You are amazing..!

2023-04-26 16:46 UTC, kjappelbaum commented on data/nr_er_lbd_tox21/meta.yaml
> +          - adjective: toxic in the estrogen receptor alpha ligand binding domain assay
do we add `is toxic`?

2023-04-26 16:46 UTC, kjappelbaum commented on data/nr_er_lbd_tox21/meta.yaml
> +          - adjective: toxic in the estrogen receptor alpha ligand binding domain assay
same comments for the other files

2023-04-26 16:47 UTC, kjappelbaum requested changes
i have one question about how we should use `verb` - do we include `is` or not? Otherwise, lgtm!

2023-04-27 06:28 UTC, kjappelbaum commented on data/nr_ahr_tox21/meta.yaml
> +          - verb: activity in the aryl hydrocarbon receptor toxicity assay
```suggestion
          - verb: is active  in the aryl hydrocarbon receptor toxicity assay
```

2023-04-27 07:12 UTC, kjappelbaum commented
@MicPie I'd fix the remaining validation complains in a separate PR

2023-04-27 09:55 UTC, MicPie commented on data/nr_ar_tox21/transform.py
> +                    {"verb": "is toxic in a androgen receptor toxicity assay"},
I guess here we can remove the `is`?

2023-04-27 10:14 UTC, MicPie approved these changes
lgtm

2023-04-27 10:16 UTC, merged